### ISSUE TITLE
Create models in separate file 

### ISSUE THREAD

**Issue by iamrajhans** [cj621/DBATU-Online-Portal#1]
Move your model to separate file 
`class Students(UserMixin, db.Model):
	__tablename__ = 'students'
	id = db.Column(db.Integer, primary_key=True)
	name = db.Column(db.String(255))
	dept = db.Column(db.String(255))
	year = db.Column(db.Integer)
	email = db.Column(db.String(255))
	password = db.Column(db.String(255))`

**Comment by cj621** [comment]
created separate files for models.
Since db object cannot be used in multiple modules due to circular imports, created a separate file for initialization of db object (db_init.py).
